---
title: "figure-y"
author: "Mac Campbell"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message=FALSE)
```

```{r}
library(tidyverse)
library(ggtree)
library(ape)
```


## Look at Cytb tree
```{r}
#u<-read.tree("figure-y/cytb.phylip.contree")
u<-read.tree("figure-y/cytb.phylip.uniqueseq.phy.contree")
u2<-root(u, c("AF549116_1_1_1057_Cottus_beldingi_isolate_CBG03_cy","AF549117_1_1_1057_Cottus_beldingi_isolate_CBG04_cy","AY833337_1_1_1050_Cottus_beldingii_cytochrome_b__c"))

u3<-as.polytomy(u2, feature='node.label', fun=function(x) as.numeric(x) < 70)
#u3<-u2
t<-ggtree(u3, layout = "rectangular")
t$data$Bootstrap<-as.numeric(t$data$label)

d <- t$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label > 90,]

e <- t$data
e <- e[!e$isTip,]
e$label <- as.numeric(e$label)
e <- e[e$label < 90,]
e <- e[e$label > 75,]
```

```{r}
dem<-t  +
  geom_point(data=e,  color="gray50", cex=3, alpha=0.75, pch=18) +
  geom_point(data=d,  color="black", cex=3, alpha=0.75, pch=18) +
  geom_tiplab(size=2)+
#  geom_tippoint(aes(fill=Taxon, x=x+0.01), align=TRUE, pch=21, cex=4) +
  #scale_shape_manual(values=c(21), guide=FALSE) +
  #scale_fill_manual(values=c("#DE9E66","#439AB0","#E8BEFF","#EEF1A0","#ACCC66", "grey50")) 
#  geom_tiplab(aes(color=Taxon), cex=2, align=TRUE) +
#  scale_shape_manual(values=c(21), guide=FALSE) +
 # scale_color_manual(values=c("#DE9E66","#439AB0","#E8BEFF","#EEF1A0","#ACCC66", "grey50")) +
  xlim(0,0.3)

dem 
ggsave("figure-y/test.pdf", height=12, width = 8)
```


## Get colors

```{r}
df<-t$data %>% filter(isTip==TRUE) %>% select(label)

df$taxon<-gsub("A\\w\\d*_\\d_\\d_\\d+_","",df$label) 

df$taxon<-gsub("_belding\\w+_\\w*$"," beldingii",df$taxon)

df$taxon<-gsub("\\w*Cottus_asper\\w*","Cottus asper",df$taxon)
df$taxon<-gsub("\\w*Cottus_gulosus\\w*","Cottus gulosus",df$taxon)
df$taxon<-gsub("\\w*Cottus_pitensis\\w*","Cottus pitensis",df$taxon)

df
```

```{r}
anno<-df %>%  filter(taxon %in% c("Cottus gulosus","Cottus pitensis")) %>% separate(label, sep="_", remove=FALSE,
                                                                                    into=c("Accession","Version","Genus","Species","Isolate","Location","Gene") ) %>%
  select(-taxon)
anno$Location<-gsub("\\d","",anno$Location)
anno
```

```{r}
anno2<-anno %>% mutate(Taxon=ifelse(Location %in% c("Uvas","Guadalupe","Penitencia"), "C. o. ohlone", 
                             ifelse(Location %in% c("RR"), "C. o. pomo",
                             ifelse(Location %in% c("Upper","Kaweah","Merced","Mokelumne","Stanislaus"), "C. g. gulosus", #dropped "SF", "NMF" Feather,
                             ifelse(Species =="pitensis", "C. pitensis","C. g. wintu")))))
anno2
```


```{r}
dem<-ggtree(u3, layout = "rectangular")  %<+% anno2

dem+
  geom_point(data=e,  color="gray50", cex=4, alpha=0.75, pch=18) +
  geom_point(data=d,  color="black", cex=4, alpha=0.9, pch=18) +
  geom_tippoint(aes(x=x+0.002, fill=Taxon),cex=3, pch=21, alpha=0.85) +
  scale_fill_manual(labels=c("C. g. gulosus","C. g. wintu", "C. o. ohlone","C. o. pomo", "C. pitensis","Other"), values=c("#DE9E66","#439AB0","#E8BEFF","#EEF1A0","#ACCC66", "grey50")) +
  geom_treescale() 
  

ggsave("figure-y/tree.jpeg", width=5, height=6)
ggsave("figure-y/tree2.pdf", width=5, height=6)

  
```


